# Author: Sovereignty A.R.T.I.A.
# Description: JC21/NGINX docker compose file.
# License: BSD 3-Clause © 2024 | (https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md)

---
version: '3'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - sovbridge
    env_file: ./.env
    volumes:
      - /opt/nginx/data:/data
      - /opt/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginxdb
    restart: unless-stopped

  nginxdb:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - /opt/mysql/nginx/data:/var/lib/mysql
    networks:
     - sovbridge 
networks:
  sovbridge:
    external: True
...

### OFFICIAL INSTRUCTIONS ---> https://develop.nginxproxymanager.com/setup/ <---
