# Author: Sovereignty A.R.T.I.A.
# Description: Lidarr docker compose file.
# License: BSD 3-Clause © 2024 | (https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md)

---
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - .env
    volumes:
      - /opt/lidarr/config:/config
      - /home/bob/downloads/music:/music #optional
      - /opt/qtorrent/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

...
