#/!*!*---->This Source Code Form is subject to the terms of the The BSD 3-Clause License. If a copy of the license was not distributed with this file, You can obtain one at https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md.<----*!*!\

---
version: "2.1"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=988
      - PGID=988
      - TZ=America/Anchorage
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config/config:/config
      - /opt/duplicati/backups:/backups
      - /opt/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped

...