---

version: "3"
services:
  metube:
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /path/to/downloads:/downloads

....