#/!*!*---->This Source Code Form is subject to the terms of the The BSD 3-Clause License. If a copy of the license was not distributed with this file, You can obtain one at https://github.com/SovARTIA/Public/main/LICENSES/BSD-3-Clause.md.<----*!*!\

---
version: "3"

services:
  metube:
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /path/to/downloads:/downloads
....