# Author: Sovereignty A.R.T.I.A.
# Description: MeTube docker compose file.
# License: BSD 3-Clause © 2024 | (https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md)

---
version: "3"

services:
  metube:
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - MKNOD
      - CHOWN
      - SETGID
      - SETUID
    image: alexta69/metube
    env_file:
      - stack.env
    container_name: metube
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - /public/downloads:/downloads
...