#/!*!*---->This Source Code Form is subject to the terms of the The BSD 3-Clause License. If a copy of the license was not distributed with this file, You can obtain one at https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md.<----*!*!\

---
version: '3'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - sovbridge
    environment:
      - TZ=America/Anchorage
      - DB_MYSQL_HOST=nginxdb
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=nginx
      - DB_MYSQL_PASSWORD=%YKhG4yCosDKKX&UXb#2z4ir76Zmkk8&Zi9ZEqsv7ZXUzSUDLyT8TLtwDd&gPBN&
      - DB_MYSQL_NAME=nginxdb
    volumes:
      - /opt/nginx/data:/data
      - /opt/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginxdb
    restart: unless-stopped

  nginxdb:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'rUkgv6yajJcqyEXk%LnNs&ubQrizYVmUq4^MHmS3dML&#5#LK%jTWEa3sXxxgtoBqsWq3rjbP9Vt5vCkJdazhV2k9B3o7W5RNzxbQMugC^Lb8%nN@3@vTDK8kWXJT@JX'
      MYSQL_DATABASE: 'nginxdb'
      MYSQL_USER: 'nginx'
      MYSQL_PASSWORD: '%YKhG4yCosDKKX&UXb#2z4ir76Zmkk8&Zi9ZEqsv7ZXUzSUDLyT8TLtwDd&gPBN&'
    volumes:
      - /opt/mysql/nginx/data:/var/lib/mysql
    networks:
     - sovbridge 
networks:
  sovbridge:
    external: True
...
