#/!*!*---->This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.<----*!*!\

---
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - USER_UID=988 #whatever you want the uid to be
      - USER_GID=988 #whatever you want the gid to be
    ports:
      - "8080:8080"
    volumes:
      - trilium:/home/node/trilium-data
...