#/!*!*---->This Source Code Form is subject to the terms of the The MIT License (MIT). If a copy of the MIT was not distributed with this file, You can obtain one at https://mit-license.org/.<----*!*!\

---
version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=604800
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
...
