#/!*!*---->This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.<----*!*!\

---
version: '3'
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - /opt/handbrake/config:/config
      - /home/bob/handbrake:/storage:ro
      - /home/bob/handbrake/watch:/watch
      - /home/bob/handbrake/output:/output
...