#/!*!*---->This Source Code Form is subject to the terms of the The BSD 3-Clause License. If a copy of the license was not distributed with this file, You can obtain one at https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md.<----*!*!\

---
version: '3'
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - /opt/handbrake/config:/config
      - /home/bob/handbrake:/storage:ro
      - /home/bob/handbrake/watch:/watch
      - /home/bob/handbrake/output:/output
...