# Author: Sovereignty A.R.T.I.A.
# Description: Radarr docker compose file.
# License: BSD 3-Clause © 2024 | (https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md)
---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .env
    volumes:
      - /opt/radarr/config:/data/config
      - /home/bob/downloads/videos:/data/movies #optional
   #   - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

...