# Author: Sovereignty A.R.T.I.A.
# Description: Rancher docker compose file.
# License: BSD 3-Clause © 2024 | (https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md)

---
version: '3'

services:

 rancher:
   container_name: rancher
   image: rancher/rancher
   privileged: true
   ports:
    - 80:80
    - 443:443
   restart: unless-stopped

...