#/!*!*---->This Source Code Form is subject to the terms of the The MIT License (MIT). If a copy of the MIT was not distributed with this file, You can obtain one at https://mit-license.org/.<----*!*!\

---
version: "3"
services:
   adguardhome:
     image: adguard/adguardhome:latest
     container_name: adguardhome
     ports:
       - 53:53/tcp
       - 53:53/udp
       - 784:784/udp
       - 853:853/tcp
       - 3000:3000/tcp
       - 83:80/tcp
     volumes:
       - /opt/adguard/work:/opt/adguardhome/work
       - /opt/adguard/conf:/opt/adguardhome/conf
     restart: unless-stopped
...    
