# Author: Sovereignty A.R.T.I.A.
# Description: Duplicati docker compose file.
# License: BSD 3-Clause © 2024 | (https://github.com/SovARTIA/Public/blob/main/LICENSES/BSD-3-Clause.md)

---
version: "2.1"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    env_file: 
      - .env
    volumes:
      - /opt/duplicati/config/config:/config
      - /opt/duplicati/backups:/backups
      - /opt/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped

...